---

- name: Create '{{ group }}' group
  ansible.builtin.group:
    name: '{{ group }}'
    state: present

- name: Add the user '{{ user }}' to the group '{{ group }}'
  ansible.builtin.user:
    name: '{{ user }}'
    groups: '{{ group }}'
    append: yes

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: '{{ dest_dir }}'
    owner: '{{ user }}'
    group: '{{ group }}'
    mode: '2775'

- name: Install lamp-mariadb10.2-php7.2 and php7.2
  command: sudo amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2
  when:
    - { ansible_distribution == "Amazon" }

- name: Install a list of packages (php-mbstring php-xml)
  become: yes
  yum:
    name:
      - php-mbstring
      - php-xml
    state: present
  notify:
    - nginx_restart
    - php_fpm_restart
  when:
    - { ansible_distribution == "Amazon" }

- name: Make directory for phpMyadmin
  ansible.builtin.file:
    path: '{{ dest_dir }}/phpMyAdmin'
    state: directory
    owner: '{{ user }}'
    group: '{{ group }}'
    mode: '0775'

- name: Unarchive a file that needs to be downloaded
  ansible.builtin.unarchive:
    src: '{{ url_phpmyadmin }}'
    dest: '{{ dest_dir }}/phpMyAdmin'
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Run python script and make config file for phpMyadmin
  local_action: shell '{{ path_to_python_script }}/set_db_to_phpmyadmin.py' --aws_ec2 '{{ path_to_aws_ec_2 }}' --sample '{{ path_to_python_script }}/config.sample.inc.php' --config '{{ path_to_python_script }}/config.inc.php'
#  ansible.builtin.shell: python3 /home/local/DO/anton.lukashov/PycharmProjects/dev_pro_education/education/HW_dev_pro/education_ansible/roles/install_phpmyadmin/templates/set_db_to_phpmyadmin.py --aws_ec2 /home/local/DO/anton.lukashov/PycharmProjects/dev_pro_education/education/HW_dev_pro/education_ansible/aws_ec2.yml  --sample /home/local/DO/anton.lukashov/PycharmProjects/dev_pro_education/education/HW_dev_pro/education_ansible/roles/install_phpmyadmin/templates/config.sample.inc.php --config /home/local/DO/anton.lukashov/PycharmProjects/dev_pro_education/education/HW_dev_pro/education_ansible/roles/install_phpmyadmin/templates/config.inc.php

#  ansible.builtin.shell: python3 /home/local/DO/anton.lukashov/PycharmProjects/dev_pro_education/education/HW_dev_pro/education_ansible/roles/install_phpmyadmin/templates/set_db_to_phpmyadmin.py python3 set_db_to_phpmyadmin.py --aws_ec2 /home/local/DO/anton.lukashov/PycharmProjects/dev_pro_education/education/HW_dev_pro/education_ansible/aws_ec2.yml  --sample /home/local/DO/anton.lukashov/PycharmProjects/dev_pro_education/education/HW_dev_pro/education_ansible/roles/install_phpmyadmin/templates/config.sample.inc.php --config /home/local/DO/anton.lukashov/PycharmProjects/dev_pro_education/education/HW_dev_pro/education_ansible/roles/install_phpmyadmin/templates/config.inc.php

- name: Set config file to
  ansible.builtin.copy:
    src: templates/config.inc.php
    dest: '{{ dest_dir }}/phpMyAdmin'
    mode: '0775'
  notify:
    - nginx_restart
    - php_fpm_restart