---

ansible_connection: ssh
ansible_user: ec2-user
#ansible_ssh_private_key_file: /home/local/DO/anton.lukashov/Downloads/AWS_keypair/Dnipro-KP.pem
ansible_ssh_private_key_file: secret_key.pem
ansible_python_interpreter: /usr/bin/python