
pipeline {
    agent none

    environment {
        aws_secret = credentials('AWS_SECRET_KEY')
        aws_id = credentials('AWS_ID_KEY')
    }

    stages {
        stage ('Prepare instance for AWS') {
        agent {
            label 'Trinity'
        }
        steps {
            sh 'export AWS_ACCESS_KEY_ID=$aws_id'
            sh 'export AWS_SECRET_ACCESS_KEY=$aws_secret'
            sh 'export AWS_DEFAULT_REGION=eu-central-1'
            }
        }

        stage ('Install boto3') {
        agent {
            label 'Trinity'
        }
        steps {
            sh 'pip3 install boto3'
            sh 'pip3 install botocore'
            sh 'ansible-galaxy collection install amazon.aws'
            }
        }

        stage ('Install git') {
        agent {
            label 'Trinity'
        }
        steps {
            sh 'apt install git -y'
            }
        }

        stage ('Pull git repo') {
        agent {
            label 'Trinity'
        }
        steps {
            sh 'cd /root/git_repo && git pull'
            }
        }

        stage ('aws_cli') {
        agent {
            label 'Trinity'
        }
        steps {
            sh 'cd /root/git_repo/HW_dev_pro/education_ansible && ansible-vault decrypt secret_key.pem --vault-password-file /tmp/test.txt || echo "The secret_key has already decrypted" '
            sh 'cd /root/git_repo/HW_dev_pro/education_ansible && ansible-inventory -i aws_ec2.yml --list'
            }
        }

    }
}