
pipeline {
    agent none

    stages {
        stage ('Pull git repo') {
        agent {
            label 'Trinity'
        }
        steps {
            sh 'cd /root/git_repo && git pull'
            }
        }

        stage ('decrypt secret_key.pem') {
        agent {
            label 'Trinity'
        }
        steps {
            sh 'cd /root/git_repo/HW_dev_pro/education_ansible && ansible-vault decrypt secret_key.pem --vault-password-file /tmp/test.txt || echo "The secret_key has already decrypted" '
            }
        }

        stage ('terraform') {
        agent {
            label 'Trinity'
        }
        steps {
            sh 'cd /root/git_repo/HW_dev_pro/education_terraform/blue-green && terraform apply -auto-approve'
            sh 'sleep 2m'
            }
        }

        stage ('Ansible') {
        agent {
            label 'Trinity'
        }
        steps {
            sh 'cd /root/git_repo/HW_dev_pro/education_ansible && ansible-playbook -i aws_ec2.yml play.yml'
            }
        }
    }
}